#%RAML 1.0
title: employee

description: this is employess api. get records and post employee records in this api.

securitySchemes:
  basic:
    type: Basic Authentication
  oauth:
    type: OAuth 2.0
  
securedBy:
  - basic
  - oauth

traits:
  client-id-required:
    headers:
      client_id:
        type: string
        required: false
      client_secret:
        type: string
        required: false

/getemployee:
  get: 
    is: [client-id-required]
    responses:
      200:
        body:
          application/json:
            example: | 
              {
              "EmpName" : "Vijay Sunkara",
              "Age" : "37",
              "Location": "Hyderabad",
              "JobTitle": "Dev team lead",
              "salary" : "50000"
              }

/createmployee:
  post:
    body:
      application/json:
        example: |
          {
              "EmpName" : "Vijay Sunkara",
              "Age" : "37",
              "Location": "Hyderabad",
              "JobTitle": "Dev team lead",
              "salary" : "50000"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "Status": "Successfully record created"
              }

            